logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/secondhand
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:never}
      schema-locations: "classpath:database-init.sql"
  cache:
    redis:
      time-to-live: 10S
    type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher

gcs:
  bucket: "secondhand-bucket"

jwt:
  secret: "secret"

elasticsearch:
  address: "34.16.170.100:9200"
  username: "elyse"
  password: "12345678"




