logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL

spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/secondhand
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      # always??????run server? database?????
      # better never init database, beacause we may upload many images to gcs
      mode: ${INIT_DB:never}
      schema-locations: "classpath:database-init.sql"

gcs:
  bucket: "secondhand-item-images"
